/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package org.primefaces.plantillas;

import javax.swing.JPanel;
import org.openide.awt.*;

public final class masterdetailVisualPanel1 extends JPanel {

    /**
     * Creates new form masterdetailVisualPanel1
     */
    static final String TITLE = "Title";
    static final String MASTER = "Master";
    static final String DETALLE = "Detalle";
    public masterdetailVisualPanel1() {
        initComponents();
    }

    @Override
    public String getName() {
        return "título";
    }

    public String getTitle() {
        return jtxtTitle.getText();
    }

    public String getMaster() {
        return jtxtMaster.getText();
    }

    public String getDetalle() {
        return jtxtdetalle.getText();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jtxtTitle = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        jtxtMaster = new javax.swing.JTextField();
        jtxtdetalle = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();

        org.openide.awt.Mnemonics.setLocalizedText(jLabel1, org.openide.util.NbBundle.getMessage(masterdetailVisualPanel1.class, "masterdetailVisualPanel1.jLabel1.text")); // NOI18N

        jtxtTitle.setText(org.openide.util.NbBundle.getMessage(masterdetailVisualPanel1.class, "masterdetailVisualPanel1.jtxtTitle.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel2, org.openide.util.NbBundle.getMessage(masterdetailVisualPanel1.class, "masterdetailVisualPanel1.jLabel2.text")); // NOI18N

        jtxtMaster.setText(org.openide.util.NbBundle.getMessage(masterdetailVisualPanel1.class, "masterdetailVisualPanel1.jtxtMaster.text")); // NOI18N

        jtxtdetalle.setText(org.openide.util.NbBundle.getMessage(masterdetailVisualPanel1.class, "masterdetailVisualPanel1.jtxtdetalle.text")); // NOI18N

        org.openide.awt.Mnemonics.setLocalizedText(jLabel3, org.openide.util.NbBundle.getMessage(masterdetailVisualPanel1.class, "masterdetailVisualPanel1.jLabel3.text")); // NOI18N

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jtxtdetalle)
                    .addComponent(jtxtMaster)
                    .addComponent(jtxtTitle, javax.swing.GroupLayout.DEFAULT_SIZE, 99, Short.MAX_VALUE))
                .addContainerGap(213, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jtxtTitle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtMaster, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jtxtdetalle, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addContainerGap(217, Short.MAX_VALUE))
        );

        jtxtdetalle.getAccessibleContext().setAccessibleName(org.openide.util.NbBundle.getMessage(masterdetailVisualPanel1.class, "masterdetailVisualPanel1.jtxtdetalle.AccessibleContext.accessibleName")); // NOI18N
        jtxtdetalle.getAccessibleContext().setAccessibleDescription(org.openide.util.NbBundle.getMessage(masterdetailVisualPanel1.class, "masterdetailVisualPanel1.jtxtdetalle.AccessibleContext.accessibleDescription")); // NOI18N
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JTextField jtxtMaster;
    private javax.swing.JTextField jtxtTitle;
    private javax.swing.JTextField jtxtdetalle;
    // End of variables declaration//GEN-END:variables
}
